import { expect, test } from "@playwright/test";
import { goToQueryLab, goToEvidenceBoard, logClueRow, logClueForRowContaining, openStudentMode, runQuery } from "./studentModeHarness";

const API = process.env.VITE_API_BASE_URL ?? "http://127.0.0.1:3001";
test("Case 001 uses durable ordered proof and retains custom drafts and archived attempts", async ({ page }) => {
  test.skip(process.env.CASE_001_LIVE_SMOKE !== "1", "Set CASE_001_LIVE_SMOKE=1 with protected runtime configured; use disposable bootstrap harness.");
  await page.goto("/");
  await page.evaluate(() => { localStorage.setItem("sequel-city.case-001.student-state.v1", JSON.stringify({ version: 1, caseId: "case-001", state: { studentDraftQuery: "legacy draft", evidenceQueries: { "case-001-report-interviews-located": "fake" }, notebookEntries: [{ detail: "legacy note" }] } })); localStorage.setItem("wp288-unrelated", "keep"); });
  await page.getByRole("button", { name: "Select Case 001: The Clocktower Poisoning" }).click();
  await page.getByRole("button", { name: "Open Case File", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Case 001 Briefing" })).toBeVisible();
  await expect(page.getByLabel("Whole case briefing")).toContainText("Determine who committed the crime");
  await page.getByRole("button", { name: "Open Query Lab" }).click();
  const guidance = page.getByLabel("Samuel's Guidance");
  const editor = page.getByLabel("SQL Query", { exact: true });
  await expect(guidance).toContainText("Start with CrimeType");
  await expect(guidance).not.toContainText("Nice work finding");
  await expect(editor).toHaveValue("");
  await page.screenshot({ path: "test-results/wp288-query-lab.png", fullPage: true });
  await page.getByRole("button", { name: "Use starter", exact: true }).click();
  await expect(editor).toHaveValue("SELECT * FROM CrimeType;");
  const run = async (sql: string) => {
    await editor.fill(sql);
    const response = page.waitForResponse(r => r.url().includes("/api/attempts/") && r.url().endsWith("/query"));
    await page.getByRole("button", { name: "Run Query", exact: true }).click();
    const result = await (await response).json();
    expect(result.progressSaved, result.message).toBe(true);
    return result;
  };
  const crime = await run("SELECT * FROM CrimeType;");
  expect(crime.snapshot.progress.completed).toBe(1);
  await expect(guidance).toContainText("Carry the CrimeID you observed");
  await expect(editor).toHaveValue("SELECT * FROM CrimeType;");
  const broadSql = "SELECT * FROM CrimeSceneReport WHERE CrimeID = 1080;";
  const broad = await run(broadSql);
  expect(broad.data.rowCount).toBeGreaterThan(1); expect(broad.snapshot.task.stepKey).toBe("clocktower-report");
  await expect(editor).toHaveValue(broadSql);
  await expect(guidance).not.toContainText("The report gives us a trail");
  const report = await run("SELECT * FROM CrimeSceneReport WHERE CrimeID = 1080 AND ReportCity = 'Sequel City' AND ReportDate = 20230502;");
  expect(report.data.rowCount).toBe(1); expect(report.snapshot.progress.completed).toBe(2);
  const reportId = report.snapshot.facts.find((f: { key: string }) => f.key === "ReportID").value;
  const interviews = await run(`SELECT * FROM InterviewLog WHERE ReportID = ${reportId};`);
  expect(interviews.snapshot.progress.completed).toBe(3); expect(interviews.snapshot.status).toBe("completed");
  await expect(guidance).toContainText("identifying and verifying the culprit belongs to a later release");
  await page.getByRole("button", { name: "Log row 1 as evidence", exact: true }).click();
  await expect(page.getByText("Row logged to your saved notebook.").first()).toBeVisible();
  const custom = "SELECT PersonID FROM InterviewLog ORDER BY PersonID; -- my retained draft";
  await editor.fill(custom);
  await page.getByRole("button", { name: "Save workspace", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save workspace", exact: true })).toBeEnabled();
  await page.reload();
  if (await page.getByRole("button", { name: "Select Case 001: The Clocktower Poisoning" }).isVisible()) await page.getByRole("button", { name: "Select Case 001: The Clocktower Poisoning" }).click();
  await page.getByRole("button", { name: "Resume Case File", exact: true }).click();
  await page.getByRole("button", { name: "Query Lab", exact: true }).click();
  await expect(editor).toHaveValue(custom);
  await expect(guidance).toContainText("identifying and verifying the culprit belongs to a later release");
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Start Fresh", exact: true }).click();
  await page.getByRole("button", { name: "Open Query Lab", exact: true }).click();
  await expect(guidance).toContainText("Start with CrimeType"); await expect(editor).toHaveValue("");
  expect(await page.evaluate(() => localStorage.getItem("wp288-unrelated"))).toBe("keep");
  expect(await page.evaluate(() => localStorage.getItem("sequel-city.case-001.student-state.v1"))).toContain("legacy draft");
  const summaries = await page.evaluate(async api => (await fetch(`${api}/api/cases/case-001/attempts`, { credentials: "include" })).json(), API);
  expect(summaries.attempts.some((s: { status: string; progress: { completed: number } }) => s.status === "completed" && s.progress.completed === 3)).toBe(true);
});

test("Case 004 legacy adapter still executes real evidence and controlled suspect verification", async ({ page }) => {
  test.skip(process.env.CASE_001_LIVE_SMOKE !== "1", "Requires the disposable live SQL stack.");
  await openStudentMode(page);
  await goToQueryLab(page);
  await runQuery(page, "SELECT * FROM CrimeType WHERE CrimeType='Murder';");
  await logClueRow(page, 1);
  await runQuery(page, "SELECT * FROM CrimeSceneReport WHERE CrimeID=1080 AND ReportCity='SQL City' AND ReportDate=20230115;");
  await logClueRow(page, 1);
  await runQuery(page, "SELECT * FROM InterviewLog WHERE ReportID=10975 ORDER BY PersonID;");
  await logClueRow(page, 1);
  await logClueRow(page, 5);
  await runQuery(page, "SELECT * FROM PersonsOfInterest WHERE PersonID IN (14887,16371) ORDER BY PersonID;");
  await logClueRow(page, 1); await logClueRow(page, 2);
  await runQuery(page, "SELECT * FROM FitNFlabClub WHERE FitMembershipStatus='gold' AND FitMemberID LIKE '48Z%';");
  await logClueForRowContaining(page, "67318");
  await runQuery(page, "SELECT * FROM PersonsOfInterest WHERE PersonID=67318;"); await logClueRow(page, 1);
  await runQuery(page, "SELECT * FROM InterviewLog WHERE PersonID=67318 AND ReportID=10975;");
  await logClueForRowContaining(page, "Listen, dime-store cop");
  await goToEvidenceBoard(page);
  await page.getByRole("radio", { name: "Jeremy Bowers" }).check();
  const verification = page.waitForResponse(r => r.url().endsWith("/api/case/verify-suspect") && r.status() === 200);
  await page.getByRole("button", { name: "Test Theory" }).click();
  expect((await (await verification).json()).success).toBe(true);
  await expect(page.getByRole("heading", { name: "First Suspect Confirmed" })).toBeVisible();
});
